module.exports = {
  rules: {
    // @see: https://commitlint.js.org/#/reference-rules
  },
  prompt: {
    alias: { fd: "docs: fix typos" },
    messages: {
      type: "コミットする変更のタイプを選択してください:",
      scope: "この変更のスコープ（範囲）を示してください（任意）:",
      customScope: "この変更のスコープ（範囲）を入力してください:",
      subject: "短く、命令形の簡潔な説明を書いてください:\n",
      body: 'より詳細な変更内容を記述してください（任意）。"|"で改行できます:\n',
      breaking: '互換性のない変更点（BREAKING CHANGES）を挙げてください（任意）。"|"で改行できます:\n',
      footerPrefixesSelect: "この変更によってクローズされるイシューのタイプを選択してください（任意）:",
      customFooterPrefix: "イシューのプレフィックス（接頭辞）を入力してください:",
      footer: "関連するイシュー番号を列挙してください（例: #31, #34）:\n",
      generatingByAI: "AIがコミット件名を生成中です...",
      generatedSelectByAI: "AIが生成した件名から適切なものを選択してください:",
      confirmCommit: "本当に上記のコミットを続行しますか？",
    },
    types: [
      {
        value: "feat",
        name: "feat:     ✨  新機能の追加",
        emoji: "✨",
      },
      { value: "fix", name: "fix:      🐛  バグの修正", emoji: "🐛" },
      {
        value: "docs",
        name: "docs:     📝  ドキュメントのみの変更",
        emoji: "📝",
      },
      {
        value: "style",
        name: "style:    💄  コードの意味に影響しない変更（フォーマット、セミコロンなど）",
        emoji: "💄",
      },
      {
        value: "refactor",
        name: "refactor: ♻️   バグ修正や機能追加ではないコードの変更",
        emoji: "♻️",
      },
      {
        value: "perf",
        name: "perf:     ⚡️  パフォーマンスを向上させるコード変更",
        emoji: "⚡️",
      },
      {
        value: "test",
        name: "test:     ✅  テストの追加または修正",
        emoji: "✅",
      },
      {
        value: "build",
        name: "build:    📦️   ビルドシステムや外部依存関係に影響する変更",
        emoji: "📦️",
      },
      {
        value: "ci",
        name: "ci:       🎡  CI（継続的インテグレーション）の設定ファイルやスクリプトの変更",
        emoji: "🎡",
      },
      {
        value: "chore",
        name: "chore:    🔨  srcやtestファイル以外への変更（雑務）",
        emoji: "🔨",
      },
      {
        value: "revert",
        name: "revert:   ⏪️  以前のコミットを取り消す",
        emoji: "⏪️",
      },
    ],
    useEmoji: true,
    emojiAlign: "center",
    useAI: false,
    aiNumber: 1,
    themeColorCode: "",
    scopes: [],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: "bottom",
    customScopesAlias: "custom",
    emptyScopesAlias: "empty",
    upperCaseSubject: false,
    markBreakingChangeMode: false,
    allowBreakingChanges: ["feat", "fix"],
    breaklineNumber: 100,
    breaklineChar: "|",
    skipQuestions: [],
    issuePrefixes: [
      { value: "closed", name: "closed:   イシューは処理されました" },
    ],
    customIssuePrefixAlign: "top",
    emptyIssuePrefixAlias: "skip",
    customIssuePrefixAlias: "custom",
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    confirmColorize: true,
    scopeOverrides: undefined,
    defaultBody: "",
    defaultIssues: "",
    defaultScope: "",
    defaultSubject: "",
  },
};